### PR TITLE
Add StrategyType.withName(.)

### PR DESCRIPTION
**Pull request by aerust**

### CODE REVIEW

**Comment by rjmac** [comment]
Why not just expose `nameMap`?

**Comment by aerust** [comment]
I suppose that would be more useful, I don't know if I like that name though. hmm

**Comment by aerust** [comment]
I kind of like the semantics of StrategyType.withName(.) more than StrategyType.nameMap.get(.) is that a bad reason?

**Comment by rjmac** [comment]
ok

**Pull request merged**
